### ISSUE TITLE
[BUG] Documentation links on Docker hub are broken

### ISSUE THREAD

**Issue by mackenzieATA** [Ealenn/Echo-Server#102]
**Describe the bug**
On the home page for this project on docker hub (https://hub.docker.com/r/ealen/echo-server) the links to documentation get 404s.
e.g. [Docker](https://ealenn.github.io/Echo-Server/pages/docker.html) (under Table of contents)
It appears to be ALL the links, not just the examples provided here.

**To Reproduce**
Click the link https://ealenn.github.io/Echo-Server/pages/docker.html and get a github 404 page

**Expected behavior**
Probably should link to here - https://github.com/Ealenn/Echo-Server#docker - at least for the example broken link

**Response**
N/A

**Additional context**
N/A

**Comment by Ealenn** [comment]
Hello @mackenzieATA Thanks for your contribution 

I just updated the README on DockerHub :)
