### ISSUE TITLE
[FEATURE] We should have option to set the content-type expected for json body

### ISSUE THREAD

**Issue by juniorb2ss** [Ealenn/Echo-Server#149]
**Is your feature request related to a problem? Please describe.**
I have a service that sends a request with `application/ld+json` header saying that the body contains a `JSON-LD`. Today the server is logging the request however without the body, as it wasn't able to parse it.

**Describe the solution you'd like**
We should have a configuration that determine which content-types should be used to understand the body as a JSON: https://github.com/Ealenn/Echo-Server/blob/master/src/app.js#L21, so I can run the `echo-server` saying that the content-type expected for json are `json` and `jsonld`

**Describe alternatives you've considered**
I forked the project and manually changed the line to be:

```js
app.use(bodyParser.json({type: ['json', 'jsonld']}));
```

**Comment by juniorb2ss** [comment]
🏓 @Ealenn

**Comment by Ealenn** [comment]
Sorry for the delay, I promise to do that soon.
