### ISSUE TITLE
[BUG] arm/v7 build contains x86_64 binaries

### ISSUE THREAD

**Issue by dnesting** [Ealenn/Echo-Server#51]
**Describe the bug**
The `arm/v7` build appears to contain an x86_64 `/usr/local/bin/node` binary.  Likely the build process didn't get the build platform propagated correctly.  This may be impacting other non-x86_64 builds as well.

**To Reproduce**
```shell
$ docker run --rm --entrypoint /bin/cat \
  ealen/echo-server:latest@sha256:0f888333c27fab959441f8e745552915e2ef662abf9570ff9237e96595709be4  \
  /usr/local/bin/node | file -
```

**Expected behavior**
I expect to see an ARM binary.

**Response**
I instead get:
```
/dev/stdin: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
```

**Additional context**
Attempting to start a pod using this image results in this error:

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by Ealenn** [comment]
Buildx does not seem to be work correctly.

**Comment by Ealenn** [comment]
@dnesting It's ok for you ? 

> Do not hesitate to re-open this ticket.
