### ISSUE TITLE
[FEATURE] Graceful shutdown on SIGTERM signal

### ISSUE THREAD

**Issue by aslafy-z** [Ealenn/Echo-Server#96]
**Is your feature request related to a problem? Please describe.**
The app does not react when receiving a SIGTERM, we have to send a SIGKILL for it to stop. Getting a SIGKILL means the app is not gracefully shutdown.
In a Kubernetes context, this means that it systematically wait for a 30s timeout before stopping the processes.

**Describe the solution you'd like**
Handle the SIGTERM signal and gracefully stop the app.

**Describe alternatives you've considered**

**Additional context**
When this app runs in a Kubernetes context (for eg.) and someone asks to stop the pod, Kubernetes will first send a SIGTERM signal to ask the app to stop by itself. If the app does not exit by itself, it waits for a timeout (`terminationGracePeriod`, defaults to 30s) before sending a SIGKILL signal that asks the system to stop the process forcibly.  See https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace.

**Comment by Ealenn** [comment]
Hello @aslafy-z 

Thanks for your contribution 🙏 I really appreciate ! 

You're right. It's a good point. Your approach seem completely legit !

Let me review your MR as soon as possible.
